lexik_jwt_authentication:
  secret_key: '%kernel.project_dir%/config/jwt/private.pem'
  public_key: '%kernel.project_dir%/config/jwt/public.pem'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  token_ttl: '%env(int:JWT_TTL)%'
  token_extractors:
    authorization_header:
      enabled: true
      prefix: 'Bearer'
      name: 'Authorization'
    cookie:
      enabled: false
    query_parameter:
      enabled: false