---
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    pull_policy: never
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      DEFAULT_URI: https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: mysql://${MYSQL_USER:-project}:${MYSQL_PASSWORD:-project}@mysql:3306/${MYSQL_DATABASE:-project}?serverVersion=${MYSQL_VERSION:-8.0}&charset=${MYSQL_CHARSET:-utf8mb4}
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  mysql:
    image: mysql:${MYSQL_VERSION:-8}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-project}
      MYSQL_USER: ${MYSQL_USER:-project}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-project}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMeRoot!}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  caddy_data:
  caddy_config:
  database_data:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
