version: "3"
services:
  web:
    build:
      args:
        ENABLE_XDEBUG: 1
        APP_ENV: dev
    volumes:
      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - host.docker.internal:host-gateway
