volumes:
  volume_database_project:

services:
  app:
    image: ${IMAGE_NAME}:${TAG}
    container_name: project_app
    restart: unless-stopped
    env_file:
      - .env.prod.example
    ports:
      - "127.0.0.1:9000:9000"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: project_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - volume_database_project:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: neoodriver
      PMA_PASSWORD: NeooDriver9090
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy

  mailhog:
    profiles:
      - dev
