volumes:
  volume_database_project:
  certbot-web:
  certbot-certs:

services:
  mysql:
    image: mysql:8.0
    container_name: project_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - volume_database_project:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    image: ghcr.io/ahmedbattikh/neoodriver-backend:${TAG}
    container_name: project_web
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
    env_file:
      - .env.prod.example
    # In production, do not mount source or dev configs
    volumes:
      - certbot-web:/var/www/html/.well-known/acme-challenge
      - certbot-certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      mysql:
        condition: service_healthy

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-web:/var/www/html/.well-known/acme-challenge
      - certbot-certs:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html -d server.neoodriver.com --email admin@neoodriver.com --agree-tos --no-eff-email --force-renewal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: neoodriver
      PMA_PASSWORD: NeooDriver9090
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy

  mailhog:
    profiles:
      - dev
