# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    r2.account_id: '%env(R2_ACCOUNT_ID)%'
    r2.access_key_id: '%env(R2_ACCESS_KEY_ID)%'
    r2.secret_access_key: '%env(R2_SECRET_ACCESS_KEY)%'
    r2.bucket: '%env(R2_BUCKET)%'
    r2.endpoint: '%env(R2_ENDPOINT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Kernel.php,Tests,Controller}'

    App\Service\Storage\R2Client:
        arguments:
            $accountId: '%r2.account_id%'
            $accessKeyId: '%r2.access_key_id%'
            $secretAccessKey: '%r2.secret_access_key%'
            $bucket: '%r2.bucket%'
            $endpoint: '%r2.endpoint%'

    App\EventSubscriber\UserSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }
