# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.default_secret: '5E7nGHjU#QWE%3qnG@nm6jxeHqFR7jgV*J*'
    mailer.default_dsn: 'null://null'
    otp.default_fixed_code: '123456'
    trusted_proxies.default: '127.0.0.1,172.18.0.0/16'
    r2.default_account_id: ''
    r2.default_access_key_id: ''
    r2.default_secret_access_key: ''
    r2.default_bucket: ''
    r2.default_endpoint: ''
    bolt.default_oidc_url: 'https://oidc.bolt.eu/token'
    bolt.default_orders_url: 'https://node.bolt.eu/fleet-integration-gateway/fleetIntegration/v1/getFleetOrders'
    bolt.default_client_id: ''
    bolt.default_client_secret: ''
    bolt.default_scope: 'fleet-integration:api'

    r2.account_id: '%env(default:r2.default_account_id:R2_ACCOUNT_ID)%'
    r2.access_key_id: '%env(default:r2.default_access_key_id:R2_ACCESS_KEY_ID)%'
    r2.secret_access_key: '%env(default:r2.default_secret_access_key:R2_SECRET_ACCESS_KEY)%'
    r2.bucket: '%env(default:r2.default_bucket:R2_BUCKET)%'
    r2.endpoint: '%env(default:r2.default_endpoint:R2_ENDPOINT)%'
    otp.fixed_code: '%env(default:otp.default_fixed_code:OTP_FIXED_CODE)%'
    bolt.oidc_url: '%env(default:bolt.default_oidc_url:BOLT_OIDC_URL)%'
    bolt.orders_url: '%env(default:bolt.default_orders_url:BOLT_ORDERS_URL)%'
    bolt.client_id: '%env(default:bolt.default_client_id:BOLT_CLIENT_ID)%'
    bolt.client_secret: '%env(default:bolt.default_client_secret:BOLT_CLIENT_SECRET)%'
    bolt.scope: '%env(default:bolt.default_scope:BOLT_SCOPE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Kernel.php,Tests,Controller}'

    App\Service\Storage\R2Client:
        arguments:
            $accountId: '%r2.account_id%'
            $accessKeyId: '%r2.access_key_id%'
            $secretAccessKey: '%r2.secret_access_key%'
            $bucket: '%r2.bucket%'
            $endpoint: '%r2.endpoint%'
    App\Service\BoltService:
        arguments:
            $oidcUrl: '%bolt.oidc_url%'
            $ordersUrl: '%bolt.orders_url%'
            $clientId: '%bolt.client_id%'
            $clientSecret: '%bolt.client_secret%'
            $scope: '%bolt.scope%'

    App\Form\UserWizard\VehicleStepType:
        arguments:
            $vehicleModelsPath: '%kernel.project_dir%/public/data/all-vehicles-model.json'

    App\EventSubscriber\UserSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\EventSubscriber\PaymentOperationBalanceSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }
